### ISSUE TITLE
Issues uploading via arduino 1.8.9

### ISSUE THREAD

**Issue by darkstar007** [dadamachines/doppler#4]
I often get error messages like (but sometimes (around 5% of the time) it does sort of work):
```
Sketch uses 10592 bytes (2%) of program storage space. Maximum is 507904 bytes.
processing.app.debug.RunnerException
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:152)
	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:77)
	at processing.app.SketchController.upload(SketchController.java:732)
	at processing.app.SketchController.exportApplet(SketchController.java:703)
	at processing.app.Editor$UploadHandler.run(Editor.java:2086)
	at java.lang.Thread.run(Thread.java:748)
Caused by: processing.app.SerialException: Error touching serial port '/dev/ttyACM0'.
	at processing.app.Serial.touchForCDCReset(Serial.java:107)
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:136)
	... 5 more
Caused by: jssc.SerialPortException: Port name - /dev/ttyACM0; Method name - openPort(); Exception type - Port not found.
	at jssc.SerialPort.openPort(SerialPort.java:167)
	at processing.app.Serial.touchForCDCReset(Serial.java:101)
	... 6 more
```

**Comment by darkstar007** [comment]
And error messages like:
```
Sketch uses 10480 bytes (2%) of program storage space. Maximum is 507904 bytes.
Device       : ATSAMD51x19
Version      : v1.1 [Arduino:XYZ] Oct 12 2018 22:04:52
Address      : 0x0
Pages        : 1024
Page Size    : 512 bytes
Total Size   : 512KB
Planes       : 1
Lock Regions : 32
Locked       : none
Security     : false
BOD          : false
BOR          : true
Erase flash

Done in 7.672 seconds
Write 10736 bytes to flash (21 pages)

[                              ] 0% (0/21 pages)
[===========                   ] 38% (8/21 pages)
[======================        ] 76% (16/21 pages)
[==============================] 100% (21/21 pages)
Done in 0.062 seconds
Verify 10736 bytes of flash

[=                             ] 4% (1/21 pages)
[==                            ] 9% (2/21 pages)
[====                          ] 14% (3/21 pages)
[=====                         ] 19% (4/21 pages)
[=======                       ] 23% (5/21 pages)
[========                      ] 28% (6/21 pages)
[==========                    ] 33% (7/21 pages)
[===========                   ] 38% (8/21 pages)
[============                  ] 42% (9/21 pages)
[==============                ] 47% (10/21 pages)
[===============               ] 52% (11/21 pages)
[=================             ] 57% (12/21 pages)
[==================            ] 61% (13/21 pages)
SAM-BA operation failed
An error occurred while uploading the sketch
processing.app.SerialException: Error opening serial port '/dev/ttyACM0'.
	at processing.app.Serial.<init>(Serial.java:149)
	at processing.app.Serial.<init>(Serial.java:82)
	at processing.app.SerialMonitor$4.<init>(SerialMonitor.java:101)
	at processing.app.SerialMonitor.open(SerialMonitor.java:101)
	at processing.app.AbstractMonitor.resume(AbstractMonitor.java:104)
	at processing.app.Editor.resumeOrCloseSerialMonitor(Editor.java:2154)
	at processing.app.Editor.access$1300(Editor.java:115)
	at processing.app.Editor$UploadHandler.run(Editor.java:2120)
	at java.lang.Thread.run(Thread.java:748)
Caused by: jssc.SerialPortException: Port name - /dev/ttyACM0; Method name - openPort(); Exception type - Port busy.
	at jssc.SerialPort.openPort(SerialPort.java:164)
	at processing.app.Serial.<init>(Serial.java:138)
	... 8 more
Error opening serial port '/dev/ttyACM0'.
```

**Comment by darkstar007** [comment]
And error messages like:
```
Sketch uses 10480 bytes (2%) of program storage space. Maximum is 507904 bytes.
Device       : ATSAMD51x19
Version      : v1.1 [Arduino:XYZ] Oct 12 2018 22:04:52
Address      : 0x0
Pages        : 1024
Page Size    : 512 bytes
Total Size   : 512KB
Planes       : 1
Lock Regions : 32
Locked       : none
Security     : false
BOD          : false
BOR          : true
Erase flash

Done in 7.672 seconds
Write 10736 bytes to flash (21 pages)

[                              ] 0% (0/21 pages)
[===========                   ] 38% (8/21 pages)
[======================        ] 76% (16/21 pages)
[==============================] 100% (21/21 pages)
Done in 0.062 seconds
Verify 10736 bytes of flash

[=                             ] 4% (1/21 pages)
[==                            ] 9% (2/21 pages)
[====                          ] 14% (3/21 pages)
[=====                         ] 19% (4/21 pages)
[=======                       ] 23% (5/21 pages)
[========                      ] 28% (6/21 pages)
[==========                    ] 33% (7/21 pages)
[===========                   ] 38% (8/21 pages)
[============                  ] 42% (9/21 pages)
[==============                ] 47% (10/21 pages)
[===============               ] 52% (11/21 pages)
[=================             ] 57% (12/21 pages)
[==================            ] 61% (13/21 pages)
SAM-BA operation failed
An error occurred while uploading the sketch
processing.app.SerialException: Error opening serial port '/dev/ttyACM0'.
	at processing.app.Serial.<init>(Serial.java:149)
	at processing.app.Serial.<init>(Serial.java:82)
	at processing.app.SerialMonitor$4.<init>(SerialMonitor.java:101)
	at processing.app.SerialMonitor.open(SerialMonitor.java:101)
	at processing.app.AbstractMonitor.resume(AbstractMonitor.java:104)
	at processing.app.Editor.resumeOrCloseSerialMonitor(Editor.java:2154)
	at processing.app.Editor.access$1300(Editor.java:115)
	at processing.app.Editor$UploadHandler.run(Editor.java:2120)
	at java.lang.Thread.run(Thread.java:748)
Caused by: jssc.SerialPortException: Port name - /dev/ttyACM0; Method name - openPort(); Exception type - Port busy.
	at jssc.SerialPort.openPort(SerialPort.java:164)
	at processing.app.Serial.<init>(Serial.java:138)
	... 8 more
Error opening serial port '/dev/ttyACM0'.
```
